---
dependencies: []

galaxy_info:
  author: vpanicke
  description: Debian/Ubuntu configuration for Packer.
  company: ""
  license: "license (BSD, MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
    - cloud
    - system
    - packaging
    - development
